export type ViewMode = 'grid' | 'list';
export type UploadStatus = 'idle' | 'uploading' | 'complete' | 'error';

export interface UploadFile {
  /** Unique ID generated by the component (crypto.randomUUID()) */
  id: string;
  /** The native File object from the browser */
  file: File;
  /** Display name — user can rename this; starts as file.name without extension */
  name: string;
  /** Original filename preserved for duplicate detection */
  originalName: string;
  /** Object URL for image preview (null for video) */
  previewUrl: string | null;
  /** Formatted size string e.g. "26.2 KB" */
  formattedSize: string;
  /** MIME type shorthand for display: 'PNG', 'JPEG', 'MP4', 'WEBM' */
  typeLabel: string;
  /** Upload progress 0-100; null = not started */
  progress: number | null;
  /** Whether this file has been renamed by the user */
  renamed: boolean;
}

export interface LibraryItem {
  id: string;
  name: string;
  typeLabel: string;
  thumbnailUrl: string;
  formattedSize: string;
  uploadedAt: Date;
  /** Transloadit CDN result URL */
  url: string;
}

export interface ValidationError {
  /** ID of the UploadFile this error relates to (empty string for pre-add errors) */
  fileId: string;
  filename: string;
  type: 'unsupported-type' | 'special-chars' | 'file-too-large';
  message: string;
}

export interface DuplicateInfo {
  /** ID of the UploadFile that is a duplicate */
  fileId: string;
  /** The current name that conflicts */
  currentName: string;
  /** Suggested non-conflicting name e.g. "photo-1" */
  suggestedName: string;
  /** Whether user has resolved this duplicate */
  resolved: boolean;
}

export interface OnUploadPayload {
  status: 'uploading' | 'uploaded';
  data: TransloaditAssembly | null;
}

export interface TransloaditAssembly {
  ok: string;
  assembly_id: string;
  results: Record<string, TransloaditFile[]>;
}

export interface TransloaditFile {
  id: string;
  name: string;
  basename: string;
  ext: string;
  size: number;
  mime: string;
  url: string;
  ssl_url: string;
  meta: Record<string, unknown>;
}
